version: "3.7"

services:
  app:
    image: node:16
    container_name: node-app
    working_dir: /app
    volumes:
      - /home/deployer/node-app:/app
    command: >
      sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/deployer/node-app/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
      - cadvisor
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
