---
- name: Install Docker and Deploy Monitoring Stack
  hosts: all
  become: true
  vars:
    ansible_user: ubuntu
    docker_projects_dir: /home/ubuntu/docker_projects
    docker_compose_monitoring_file: "{{ docker_projects_dir }}/docker-compose.yaml"  
  tasks:
    # Docker and Docker Compose Installation Tasks
    - name: Update package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies for Docker
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "gnupg",
            "software-properties-common",
          ]
        state: present

    - name: Import GPG key for Docker repository
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88

    - name: Add source list for Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
        state: present  

    - name: Create a new group for the Docker socket
      group:
        name: docker
        state: present

    - name: Create a new user for the Docker socket
      user:
        name: docker
        group: docker
        shell: /bin/false
        system: yes
        create_home: no

    - name: Create a new directory for Docker Compose projects
      file:
        path: "{{ docker_projects_dir }}"
        state: directory
        mode: "0755"

    - name: Copy over Docker compose file
      copy:
        src: docker-compose.yaml
        dest: "{{ docker_compose_monitoring_file }}"

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      notify:
        - Reload systemd daemon to pick up new Docker service configuration
        - daemon-reload

    - name: Copy over Docker Compose file for Monitoring Stack
      copy:
        src: docker-compose.yaml
        dest: "{{ docker_compose_monitoring_file }}"
        mode: "0644"

    - name: Create required directories for monitoring stack
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: docker
        mode: "0755"
      loop:
        - "{{ docker_projects_dir }}/prometheus"
        - "{{ docker_projects_dir }}/grafana"
        - "{{ docker_projects_dir }}/loki"
        - "{{ docker_projects_dir }}/alertmanager"

    - name: Start Monitoring Stack using Docker Compose
      command: "docker compose -f {{ docker_compose_monitoring_file }} up -d"

  handlers:
    - name: Reload systemd daemon to pick up new Docker service configuration
      systemd:
        name: docker
        state: restarted
    - name: daemon-reload
      command: systemctl daemon-reload