version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: -config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - "3001:3000"
    restart: always
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    restart: always
    networks:
      - monitoring
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    restart: always
    networks:
      - monitoring
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yaml

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  loki-data:
    driver: local      
