global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.31.5.171:8080']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['monitoring.ches-it.com:9093']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.31.5.171:9100']
  - job_name: "prod-servers"
    ec2_sd_configs:
      - port: 9100
        filters:
          - name: "tsg:Environment"
            values: ["prod"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
      - source_labels: [__meta_ec2_instance_id]
        target_label: __instance__
